backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: 'src/assets'
public_folder: '/assets'

collections:
  - name: 'note'
    label: 'Note'
    folder: 'src/pages/note'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: '../../src/layouts/NotePage.astro'
        }
      - { label: 'Note Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime' }
      - { label: 'Note Banner', name: 'heroImage', widget: 'image' }
      - { label: 'Write Your Note', name: 'body', widget: 'markdown' }
